# Append CPPFLAGS with additional stuff
CPPFLAGS += -std=c++11 -g

# Indicate where we are relative to the top of the source tree.
LEVEL=../..

# Give the name of a library.  This will build a dynamic version.
LIBRARYNAME=DependenceCheck

# Make the librray load (ie loadable by opt)
LOADABLE_MODULE = 1

# Include Makefile.common so we know what to do.
include $(LEVEL)/Makefile.common
